apiVersion: v1
kind: Namespace
metadata:
  name: mathgarage
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: sample
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-space
  labels:
    istio-injection: enabled