apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
    env: sandbox
    provisioned_by: kcc
  name: grafana
  namespace: monitoring
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: grafana
    env: sandbox
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
    env: sandbox
    provisioned_by: kcc
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      env: sandbox
  template:
    metadata:
      labels:
        app: grafana
        env: sandbox
        provisioned_by: kcc
    spec:
      containers:
      - envFrom: null
        image: grafana/grafana:latest
        name: grafana
        ports:
        - containerPort: 3000
          name: web-0
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      serviceAccountName: ksa-monitoring
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  labels:
    app: grafana
    env: sandbox
    provisioned_by: kcc
  name: grafana
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: metrics
  - interval: 10s
    path: /stats/prometheus
    port: 15020
    scheme: http
  selector:
    matchLabels:
      app: grafana
      env: sandbox
