apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-api
    env: sandbox
    provisioned_by: kcc
  name: hello-world-api
  namespace: sample
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-world-api
    env: sandbox
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-api
    env: sandbox
    provisioned_by: kcc
  name: hello-world-api
  namespace: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-api
      env: sandbox
  template:
    metadata:
      labels:
        app: hello-world-api
        env: sandbox
        provisioned_by: kcc
    spec:
      containers:
      - envFrom: null
        image: docker.io/jaichenchlani/hello-world-api:0.3
        name: hello-world-api
        ports:
        - containerPort: 8080
          name: http-0
          protocol: TCP
        resources:
          limits:
            cpu: 10m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 32Mi
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  labels:
    app: hello-world-api
    env: sandbox
    provisioned_by: kcc
  name: hello-world-api
  namespace: sample
spec:
  endpoints:
  - interval: 30s
    port: metrics
  - interval: 10s
    path: /stats/prometheus
    port: 15020
    scheme: http
  selector:
    matchLabels:
      app: hello-world-api
      env: sandbox
