apiVersion: v1
kind: Service
metadata:
  labels:
    app: multiply-api
    env: sandbox
    provisioned_by: kcc
  name: multiply-api
  namespace: sample
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: multiply-api
    env: sandbox
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multiply-api
    env: sandbox
    provisioned_by: kcc
  name: multiply-api
  namespace: sample
spec:
  selector:
    matchLabels:
      app: multiply-api
      env: sandbox
  template:
    metadata:
      labels:
        app: multiply-api
        env: sandbox
        provisioned_by: kcc
    spec:
      containers:
      - envFrom: null
        image: docker.io/jaichenchlani/multiply-api:0.1
        name: multiply-api
        ports:
        - containerPort: 8080
          name: http-0
          protocol: TCP
        resources:
          limits:
            cpu: 10m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 32Mi
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: multiply-api
    env: sandbox
    provisioned_by: kcc
  name: multiply-api
  namespace: sample
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: multiply-api
---
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  labels:
    app: multiply-api
    env: sandbox
    provisioned_by: kcc
  name: multiply-api
  namespace: sample
spec:
  endpoints:
  - interval: 30s
    port: metrics
  - interval: 10s
    path: /stats/prometheus
    port: 15020
    scheme: http
  selector:
    matchLabels:
      app: multiply-api
      env: sandbox
